# docker-compose.production.yml
version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    env_file: ../.env
    container_name: backend
    build:
      context: ../backend
      dockerfile: Dockerfile
    depends_on:
      - db
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/


  frontend:
    container_name: frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    env_file:
      - ../.env
    depends_on:
      - backend
