# docker-compose.production.yml
version: '3.9'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: db
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
  
  backend:
    env_file: ../.env
    container_name: backend
    image: kenshinlove/foodgram_backend
    depends_on:
      - db
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
  
  frontend:
    container_name: frontend
    image: kenshinlove/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/
  
  nginx:
    container_name: nginx
    image: nginx:1.19.3
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: nginx.conf
        target: /etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/var/html/static/
      - media:/var/html/media/
    depends_on:
      - backend
